server:
  port: 3000
  servlet:
    context-path: /market-mate
spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:admin}
    password: ${RABBIT_PASSWORD:admin}
    exchange: ${RABBIT_EXCHANGE:domain_events}
  application:
    name: intelliZen-market-mate
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/intelliZen
          jwk-set-uri: http://localhost:8080/realms/intelliZen/protocol/openid-connect/certs
  data:
    mongodb:
      uri: ${MONGODB_URL:}
      database: ${MONGODB_DATABASE:market-mate}
      auto-index-creation: false
      uuid-representation: standard
      authentication-database: admin
management:
  endpoint:
    health:
      probes:
        enabled: true
logging:
  pattern:
    console: "%d{ISO8601} %red([%thread]) %highlight(%-5level) %logger : %msg%n"
    file: "%d{ISO8601} %red([%thread]) %highlight(%-5level) %logger : %msg%n"
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO
market-mate:
  s3:
    bucket: ${S3_BUCKET:marketmates3}
    region: ${S3_REGION:eu-central-1}
    access-key: ${S3_ACCESS_KEY:}
    secret-key: ${S3_SECRET_KEY:}
  jwt:
    converter:
      resource-id: intelliZen-client
      principal-attribute: preferred_username
  security:
    cors:
      allowed-headers: "*"
      allowed-methods: "*"
      allowed-origins: "*"