server:
  port: 3000
  servlet:
    context-path: /market-mate
spring:
  application:
    name: intelliZen-market-mate
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/intelliZen
          jwk-set-uri: http://localhost:8080/realms/intelliZen/protocol/openid-connect/certs
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017}
      database: ${MONGODB_DATABASE:market-mate}
      auto-index-creation: false
      uuid-representation: standard
management:
  endpoint:
    health:
      probes:
        enabled: true
logging:
  pattern:
    console: "%d{ISO8601} %red([%thread]) %highlight(%-5level) %logger : %msg%n"
    file: "%d{ISO8601} %red([%thread]) %highlight(%-5level) %logger : %msg%n"
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO
market-mate:
  jwt:
    converter:
      resource-id: intelliZen-client
      principal-attribute: preferred_username
  security:
    cors:
      allowed-headers: "*"
      allowed-methods: "*"
      allowed-origins: "*"